### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by tjorim** [myTselection/Carbu_com#18]
```
Logger: homeassistant.components.sensor
Source: custom_components/carbu_com/utils.py:46
Integration: Sensor (documentation, issues)
First occurred: 2:19:52 AM (3 occurrences)
Last logged: 2:19:52 AM

Error while setting up carbu_com platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/carbu_com/sensor.py", line 132, in async_setup_entry
    await dry_setup(hass, config, async_add_devices)
  File "/config/custom_components/carbu_com/sensor.py", line 61, in dry_setup
    await componentData._forced_update()
  File "/config/custom_components/carbu_com/sensor.py", line 199, in _forced_update
    self._carbuLocationInfo = await self._hass.async_add_executor_job(lambda: self._session.convertPostalCode(self._postalcode, self._country, self._town))
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/carbu_com/sensor.py", line 199, in <lambda>
    self._carbuLocationInfo = await self._hass.async_add_executor_job(lambda: self._session.convertPostalCode(self._postalcode, self._country, self._town))
  File "/config/custom_components/carbu_com/utils.py", line 46, in convertPostalCode
    if info_dict["n"].lower() == town.lower() and info_dict["c"].lower() == country.lower() and info_dict["pc"] == postalcode:
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by myTselection** [comment]
Which postal code did you use? And which Town input was provided?

**Comment by tjorim** [comment]
2300, 2440 and 2470.
Error gets logged 3 times (one time for each postal code), reload of one triggers it again.
I did not provide a town input, only upgraded.

**Comment by myTselection** [comment]
I've tried all of these, and they do seem to work well for me
![image](https://user-images.githubusercontent.com/587940/232245043-d423afb1-ca9a-4eef-b6f3-65c7bb35bfe8.png)

**Comment by tjorim** [comment]
Setting them up as new integrations works, looks like the old ones that got migrated failed.
I'll remove the existing ones and set them up again.
