### ISSUE TITLE
ImportError: cannot import name 'VERSION'

### ISSUE THREAD

**Issue by GewoonRoy** [myTselection/Carbu_com#69]
**Carbo_com**
Version: 11.2.6
Home Assistant Core: 2024.11.2

I tried to setup Carbo but keep getting the following error. I also re-installed the component and restarted after configuration.

```Logger: homeassistant.config_entries
Bron: config_entries.py:635
Eerst voorgekomen: 08:35:46 (1 gebeurtenissen)
Laatst gelogd: 08:35:46

Error setting up entry Carbu.com 7336AM Apeldoorn NL for carbu_com
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/carbu_com/__init__.py", line 75, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(config_entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2242, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1199, in async_get_platforms
    platforms[platform_name] = await future
                               ^^^^^^^^^^^^
ImportError: cannot import name 'VERSION' from 'custom_components.carbu_com' (/config/custom_components/carbu_com/__init__.py)```

**Comment by huizebruin** [comment]
Same here

**Comment by myTselection** [comment]
Sorry, stupid mistake
Will fix asap
